"""Signal CRM — Buyer Map (hardcoded data)"""
from fastapi import APIRouter, Query
from app.auth import get_current_user

from fastapi import Depends

buyer_map_router = APIRouter(prefix="/buyer-map", tags=["Buyer Map"])

BUYER_MAP = {
    "SaaS": {
        "USA": {"primary_buyer": "VP of Engineering / CTO", "secondary_buyers": ["Head of Product", "IT Director", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Fast decisions for SMB (<$10k ARR). Enterprise needs champion + economic buyer. Product-led trials work well. Security reviews mandatory for deals >$50k."},
        "Germany": {"primary_buyer": "VP of Engineering / CTO", "secondary_buyers": ["Head of Digital Transformation", "IT Director", "CDO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Germans prefer technical depth over features. Require data residency proof. Procurement-heavy. Request RFPs for deals >€50k. Works Council approval needed if tool affects employees."},
        "UK": {"primary_buyer": "Head of Technology / CTO", "secondary_buyers": ["COO", "Head of Digital", "IT Manager"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "UK buyers are pragmatic and fast. GDPR compliance required. Prefer SLAs in GBP. Strong reference culture — get UK case studies."},
        "France": {"primary_buyer": "DSI (IT Director) / CTO", "secondary_buyers": ["DG (CEO)", "Responsable Digital", "DAF"], "entry_difficulty": "hard", "typical_deal_cycle": 120, "notes": "French companies prefer French-language demos and contracts. CNIL compliance required. Government and public sector require UGAP procurement. Paris HQ decisions are slow — build internal champion first."},
        "Netherlands": {"primary_buyer": "CTO / Head of Engineering", "secondary_buyers": ["COO", "Head of IT", "Procurement Lead"], "entry_difficulty": "easy", "typical_deal_cycle": 50, "notes": "Dutch buyers are internationally oriented, English-comfortable, and decisive. AVG (GDPR) compliance required. Amsterdam tech cluster is highly networked — referrals accelerate deals."},
        "UAE": {"primary_buyer": "CTO / IT Director", "secondary_buyers": ["CEO (for SME)", "COO", "Head of Digital Transformation"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "UAE deals often go direct to CEO for SMEs. Free zone companies decide fast. Government entities are slow (6-12mo). Prefer annual contracts. Arabic UI is a differentiator."},
        "Saudi Arabia": {"primary_buyer": "Head of IT / CIO", "secondary_buyers": ["Deputy Minister (Gov)", "CTO", "Digital Transformation Director"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "Government deals require CITC/NCA compliance and data residency in KSA. Private sector faster but needs local reseller. Arabic support mandatory for gov. Vision 2030 budgets are large."},
        "Singapore": {"primary_buyer": "CTO / VP Engineering", "secondary_buyers": ["COO", "Head of IT", "CDO"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Singapore is SE Asia HQ for most MNCs. English-native, internationally minded buyers. PDPA compliance needed. MAS regulated fintech deals take longer. Strong ROI culture."},
        "Japan": {"primary_buyer": "IT Manager / Joho Shisutemu Bu", "secondary_buyers": ["CTO", "General Manager", "Bucho (Department Head)"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "Japanese deals require local partner or Japan KK entity. Decision by consensus (nemawashi). Japanese-language UI mandatory. Long POC period (3-6mo). Once won, high retention."},
        "Australia": {"primary_buyer": "CTO / Head of Technology", "secondary_buyers": ["COO", "IT Manager", "Head of Digital"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Australian buyers are direct, English-native, and fast-moving. Privacy Act compliance required. Strong preference for local support/SLA. Time zone (AEST) matters for support SLAs."},
        "Canada": {"primary_buyer": "VP Engineering / CTO", "secondary_buyers": ["COO", "IT Director", "Head of Product"], "entry_difficulty": "easy", "typical_deal_cycle": 50, "notes": "Canada mirrors US buying behavior. PIPEDA/Quebec Law 25 compliance required. French-language requirements in Quebec. Government uses PSPC procurement."},
        "Israel": {"primary_buyer": "CTO / VP R&D", "secondary_buyers": ["CEO (startup)", "Head of Product", "VP Engineering"], "entry_difficulty": "medium", "typical_deal_cycle": 30, "notes": "Israeli tech buyers are very technical and skeptical. Fast decisions if product is genuinely strong. Startup-heavy — expect aggressive negotiation. Hebrew optional but appreciated for local firms."},
        "Brazil": {"primary_buyer": "CTO / Diretor de TI", "secondary_buyers": ["CEO (SME)", "COO", "Head of Digital"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "LGPD compliance required. Portuguese-language materials strongly preferred. Nota Fiscal requirements for invoicing. Economic instability means annual contracts require finance approval."},
        "India": {"primary_buyer": "CTO / VP Engineering", "secondary_buyers": ["IT Head", "CEO (startup)", "CDO"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "India SaaS market is price-sensitive. INR pricing preferred. Large enterprise needs procurement/L1/L2. Startup ecosystem fast. DPDP Act compliance now required."},
        "South Africa": {"primary_buyer": "IT Director / CTO", "secondary_buyers": ["COO", "Head of Digital", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "POPIA compliance required. USD pricing preferred for contracts. Johannesburg and Cape Town are primary markets. Loadshedding affects SLA expectations — uptime guarantees important."},
        "Nigeria": {"primary_buyer": "CTO / Head of IT", "secondary_buyers": ["CEO (SME)", "COO", "Head of Digital"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "NDPR compliance required. Lagos-focused market. USD contracts preferred due to Naira volatility. Fintech, banking, and telecom are strongest verticals. Strong referral culture."},
        "Kenya": {"primary_buyer": "Head of IT / CTO", "secondary_buyers": ["CEO", "COO", "Digital Lead"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Growing tech hub (Silicon Savannah). English-native buyers. Data Protection Act 2019 compliance. Mobile-first expectations. Nairobi-centric decisions."},
        "Indonesia": {"primary_buyer": "CTO / Direktur IT", "secondary_buyers": ["CEO (startup)", "COO", "Manajer IT"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "PDP Law compliance required. Bahasa Indonesia materials for mid-market. Jakarta-centric. Government requires TKDN (local content) for large deals. Gojek/Tokopedia ecosystem influence."},
        "Vietnam": {"primary_buyer": "IT Director / CTO", "secondary_buyers": ["CEO (SME)", "Head of Technology", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Fast-growing digital economy. Vietnamese-language support expected for local firms. Government deals require local entity. Ho Chi Minh City and Hanoi are dual centers."},
        "Philippines": {"primary_buyer": "CTO / VP IT", "secondary_buyers": ["COO", "CEO (SME)", "Head of Digital"], "entry_difficulty": "easy", "typical_deal_cycle": 50, "notes": "English-native. Strong BPO/outsourcing sector creates IT demand. NPC (privacy regulator) compliance required. Manila-focused. Very referral-driven market."},
        "Malaysia": {"primary_buyer": "CTO / Head of IT", "secondary_buyers": ["COO", "CEO (SME)", "Digital Transformation Lead"], "entry_difficulty": "easy", "typical_deal_cycle": 50, "notes": "PDPA compliance required. English and Bahasa Malaysia buyers. MSC Status companies have special procurement. Kuala Lumpur tech hub growing fast."},
        "Thailand": {"primary_buyer": "IT Director / CTO", "secondary_buyers": ["COO", "Head of Digital", "CEO (SME)"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "PDPA (Thai) compliance required. Thai-language materials preferred. Bangkok-centric. Relationship-first culture — face-to-face meetings valued before signing."},
        "Mexico": {"primary_buyer": "Director de TI / CTO", "secondary_buyers": ["CEO (SME)", "COO", "VP Tecnología"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Spanish materials required. LFPDPPP privacy law compliance. Mexico City is primary market. Monterrey for manufacturing. US-style SaaS buying in border region companies."},
        "Argentina": {"primary_buyer": "CTO / Gerente de IT", "secondary_buyers": ["CEO", "COO", "Head of Digital"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "USD pricing essential due to peso instability. Spanish materials. Buenos Aires tech hub very active. Strong engineering talent — technical depth appreciated."},
        "Egypt": {"primary_buyer": "IT Director / CTO", "secondary_buyers": ["COO", "CEO (SME)", "Head of Digital"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Arabic materials preferred for gov. Cairo and Alexandria markets. Government deals very slow. Private sector faster. Data residency in Egypt required for some sectors."},
        "Turkey": {"primary_buyer": "CTO / BT Direktörü", "secondary_buyers": ["CEO", "COO", "Dijital Dönüşüm Direktörü"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "KVKK privacy law compliance required. Turkish-language materials for mid-market. Istanbul-focused. Currency volatility — USD/EUR contracts preferred. Strong manufacturing and retail verticals."},
        "Poland": {"primary_buyer": "CTO / Dyrektor IT", "secondary_buyers": ["COO", "Head of Digital", "CEO (SME)"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "GDPR compliance (EU). English widely spoken in tech. Warsaw and Krakow tech hubs. Strong outsourcing sector. EU structural funds create public sector budget."},
        "Sweden": {"primary_buyer": "CTO / Head of Engineering", "secondary_buyers": ["COO", "CDO", "IT Manager"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "GDPR compliance. English-native tech buyers. Stockholm is Scandinavian tech hub. Sustainability credentials matter. High trust in vendors — low legal friction."},
        "Spain": {"primary_buyer": "Director de Tecnología / CTO", "secondary_buyers": ["COO", "CDO", "Director General"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Spanish materials expected. GDPR + AEPD compliance. Madrid and Barcelona markets. Long lunch culture — relationship building matters. Siesta schedule affects availability."},
        "Italy": {"primary_buyer": "CTO / Direttore IT", "secondary_buyers": ["CEO (SME)", "COO", "Responsabile Digital"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Italian materials for mid-market. GDPR + Garante compliance. Milan (business) and Rome (gov) markets. Strong manufacturing SME base. Very relationship-driven — referrals essential."},
    },
    "Logistics": {
        "USA": {"primary_buyer": "VP of Supply Chain / COO", "secondary_buyers": ["VP Logistics", "Head of Operations", "Procurement Director"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "ROI on transit time and cost reduction drives decisions. FTL/LTL and last-mile are separate buyer personas. 3PL vs in-house is key qualifier."},
        "Germany": {"primary_buyer": "Leiter Logistik / Head of Supply Chain", "secondary_buyers": ["COO", "Einkaufsleiter (Procurement)", "Geschäftsführer (MD)"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Germany is Europe's logistics hub. DIN/ISO compliance expected. Strong preference for German-language contracts. Automotive supply chain is biggest vertical."},
        "UAE": {"primary_buyer": "Head of Logistics / COO", "secondary_buyers": ["CEO", "VP Operations", "Port Authority Contact"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Dubai is MENA logistics gateway. Jebel Ali port relationships critical. Free zone vs mainland affects tax. Government logistics entities move slowly."},
        "Singapore": {"primary_buyer": "Head of Supply Chain / COO", "secondary_buyers": ["VP Logistics", "Regional Director", "Procurement Manager"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Singapore is ASEAN logistics HQ. Port of Singapore relationships matter. MAS-regulated freight finance deals separate. Strong last-mile and cold-chain demand."},
        "India": {"primary_buyer": "Head of Logistics / VP Supply Chain", "secondary_buyers": ["COO", "CFO (cost focus)", "Plant Manager"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "GST compliance critical for cross-state movement. E-way bill integration is differentiator. Pharma cold chain and e-commerce last-mile are hot segments. Price very competitive."},
        "Netherlands": {"primary_buyer": "Head of Logistics / Supply Chain Director", "secondary_buyers": ["COO", "Procurement Manager", "Port Liaison"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Rotterdam port hub. Customs compliance for EU entry. Strong 3PL market. Dutch logistics companies are internationally oriented and quick to decide."},
        "UK": {"primary_buyer": "Head of Operations / Supply Chain Director", "secondary_buyers": ["COO", "Procurement Manager", "Head of Fulfilment"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Post-Brexit customs complexity creates demand. Strong e-commerce fulfillment sector. HMRC CDS compliance required for import/export."},
        "Saudi Arabia": {"primary_buyer": "Head of Operations / VP Logistics", "secondary_buyers": ["COO", "Procurement Director", "Zakat/Tax Manager"], "entry_difficulty": "hard", "typical_deal_cycle": 120, "notes": "ZATCA compliance required for e-invoicing. Hajj season logistics creates annual spike. Government logistics projects huge but slow. Saudi Aramco and SABIC are largest accounts."},
        "Japan": {"primary_buyer": "Butsuryu Bucho (Logistics Manager)", "secondary_buyers": ["COO", "Procurement Manager", "IT Manager"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "Just-in-time culture — precision is paramount. Local entity or Japan partner required. Very high service standards. Long relationship building before contract."},
        "Australia": {"primary_buyer": "Head of Supply Chain / COO", "secondary_buyers": ["VP Logistics", "Procurement Manager", "Operations Director"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Large geography creates strong logistics demand. Australian Border Force compliance. E-commerce growth driving last-mile demand. Remote area delivery premium."},
        "Brazil": {"primary_buyer": "Diretor de Logística / COO", "secondary_buyers": ["VP Operações", "Gerente de Supply Chain", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "ICMS (interstate tax) compliance critical. Complex customs/Receita Federal. Road logistics dominant. São Paulo and Rio primary markets. Nota Fiscal integration required."},
        "Mexico": {"primary_buyer": "Director de Logística / COO", "secondary_buyers": ["VP Operaciones", "Gerente de Supply Chain", "Aduana Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "IMMEX maquiladora compliance for border manufacturing. SAT (tax authority) integration. Nearshoring boom creating huge logistics demand. Monterrey is key industrial hub."},
        "South Africa": {"primary_buyer": "Head of Logistics / COO", "secondary_buyers": ["Supply Chain Manager", "Procurement Director", "Port Agent"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Durban port is SADC gateway. Mining and automotive are biggest verticals. Road freight dominates. Loadshedding impacts warehouse operations."},
        "Nigeria": {"primary_buyer": "Head of Operations / COO", "secondary_buyers": ["CEO (SME)", "VP Logistics", "Customs Broker"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Lagos Apapa port complexities. Strong last-mile demand in Lagos and Abuja. Fuel cost and naira instability affect pricing. Strong cash-on-delivery requirement for consumer logistics."},
        "Indonesia": {"primary_buyer": "Head of Operations / Direktur Logistik", "secondary_buyers": ["COO", "VP Supply Chain", "Island Logistics Specialist"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "17,000+ island archipelago creates unique logistics challenges. Bea Cukai (customs) compliance. Strong e-commerce last-mile demand (Tokopedia/Shopee ecosystem)."},
    },
    "Manufacturing": {
        "Germany": {"primary_buyer": "Werksleiter (Plant Manager) / COO", "secondary_buyers": ["Head of Production", "Einkaufsleiter", "CTO (Industry 4.0)"], "entry_difficulty": "medium", "typical_deal_cycle": 120, "notes": "Germany is world's top industrial market. Industry 4.0 / IIoT investment heavy. TÜV certification may be required. Mittelstand (mid-size) is primary segment — family-owned, conservative."},
        "USA": {"primary_buyer": "VP of Manufacturing / COO", "secondary_buyers": ["Plant Manager", "VP Operations", "Head of Procurement"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Reshoring trend creating new demand. ITAR compliance for defense-adjacent. Strong automation investment. Midwest and Southeast are manufacturing belt."},
        "Japan": {"primary_buyer": "Kojo-cho (Factory Director) / Seizo Bucho", "secondary_buyers": ["COO", "Procurement Manager", "QA Manager"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "Kaizen culture — incremental improvement pitch works better than disruptive. Toyota Production System references resonate. Local Japanese partner essential."},
        "India": {"primary_buyer": "Plant Manager / Head of Operations", "secondary_buyers": ["MD (owner-managed)", "COO", "Head of Procurement"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "PLI (Production Linked Incentive) scheme creating investment. SME manufacturing dominant. BIS compliance for product standards. GST e-invoicing mandate. Price-sensitive."},
        "China": {"primary_buyer": "General Manager / COO", "secondary_buyers": ["Head of Production", "Procurement Director", "CTO"], "entry_difficulty": "hard", "typical_deal_cycle": 90, "notes": "Local entity (WFOE) required for most deals. PIPL data compliance. Chinese-language essential. Guanxi (relationships) matter more than features. IP protection concerns."},
        "Mexico": {"primary_buyer": "Director de Manufactura / COO", "secondary_buyers": ["Plant Manager", "Director de Operaciones", "Gerente de Calidad"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Nearshoring boom. IMMEX/maquiladora expertise valued. Monterrey and Guadalajara manufacturing hubs. Auto, aerospace, electronics verticals strongest."},
        "South Korea": {"primary_buyer": "부장 (Division Head) / COO", "secondary_buyers": ["CTO", "Head of Production", "Procurement Manager"], "entry_difficulty": "hard", "typical_deal_cycle": 120, "notes": "Chaebol (Samsung, LG, Hyundai) dominate. Korean-language materials required. Hierarchical buying — access through right level matters. Strong quality standards culture."},
        "UK": {"primary_buyer": "Operations Director / COO", "secondary_buyers": ["Plant Manager", "Head of Engineering", "Procurement Manager"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "Automotive, aerospace, pharma are top verticals. Innovate UK grants available. Post-Brexit supply chain reshoring demand. Made in Britain branding matters."},
        "UAE": {"primary_buyer": "COO / Head of Operations", "secondary_buyers": ["CEO", "VP Manufacturing", "Procurement Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "KIZAD and industrial zones are primary. Make in Emirates initiative. Food processing and packaging strong verticals. Import-dependent — supply chain tools valued."},
        "Brazil": {"primary_buyer": "Gerente Industrial / COO", "secondary_buyers": ["Diretor de Operações", "Gerente de Produção", "Head of Supply Chain"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "São Paulo state is industrial heartland. Auto, food, pharma top verticals. ANVISA approval for pharma. High import duties make local production important. Complex labor laws."},
        "Indonesia": {"primary_buyer": "Plant Manager / Direktur Produksi", "secondary_buyers": ["COO", "Head of Operations", "Procurement Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "TKDN local content requirements for government. Batam and Karawang industrial zones. Textile, food, auto assembly top verticals. SNI standards certification required."},
        "Thailand": {"primary_buyer": "Plant Manager / COO", "secondary_buyers": ["Head of Production", "VP Operations", "QA Director"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Eastern Economic Corridor (EEC) investment. Auto (Honda, Toyota) and electronics top verticals. Thailand Plus strategy for relocating from China. BOI promotion for foreign investment."},
    },
    "IT Services": {
        "USA": {"primary_buyer": "CIO / VP IT", "secondary_buyers": ["CTO", "Head of Infrastructure", "IT Director"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Large IT services market. SOC 2 compliance required. Staff augmentation vs managed services is key qualifier. H-1B visa constraints affect staffing deals."},
        "UK": {"primary_buyer": "CIO / IT Director", "secondary_buyers": ["COO", "Head of Technology", "Infrastructure Manager"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Strong outsourcing culture. IR35 compliance for contractor arrangements. Cyber Essentials certification valued. Financial services and public sector are biggest buyers."},
        "Germany": {"primary_buyer": "CIO / IT-Leiter", "secondary_buyers": ["CTO", "Head of Infrastructure", "IT Director"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "High security standards. BSI (Federal Office for Information Security) compliance matters. Prefer German-language SLAs. Works Council approval for employee-impacting IT changes."},
        "UAE": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "COO", "Head of Digital Transformation"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Dubai Smart City initiative creates large IT demand. Government sector slowest. TDRA compliance for telecoms-related services. Free zone companies faster to decide."},
        "India": {"primary_buyer": "CIO / IT Head", "secondary_buyers": ["CTO", "VP IT", "Head of Infrastructure"], "entry_difficulty": "easy", "typical_deal_cycle": 30, "notes": "India is IT services source AND consumer. Price-sensitive domestic market. STPI/SEZ compliance for export IT firms. Strong GCC (Global Capability Center) demand."},
        "Singapore": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "COO", "Head of Cybersecurity"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "MAS TRM (Technology Risk Management) guidelines for financial sector. PDPA compliance. Strong demand for cloud migration and cybersecurity."},
        "Australia": {"primary_buyer": "CIO / IT Director", "secondary_buyers": ["CTO", "COO", "Head of Cyber"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Australian Cyber Security Centre (ACSC) guidelines. Essential Eight framework compliance. Strong cloud migration and managed services demand. Government ASD compliance for public sector."},
        "Canada": {"primary_buyer": "CIO / VP IT", "secondary_buyers": ["CTO", "COO", "Head of Infrastructure"], "entry_difficulty": "easy", "typical_deal_cycle": 50, "notes": "PIPEDA/Quebec Bill 64 compliance. Federal government uses ProServices procurement. Strong demand for cloud services and managed security. French-English bilingual for Quebec gov."},
        "Saudi Arabia": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "COO", "CISO"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "NCA cybersecurity framework compliance mandatory. ECC (Essential Cybersecurity Controls) for critical sectors. Data residency in KSA for government. Vision 2030 IT spend is enormous."},
        "Japan": {"primary_buyer": "CIO / IT部長 (IT Manager)", "secondary_buyers": ["CTO", "COO", "General Manager"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "Japanese IT services market dominated by local SIs (NTT, Fujitsu, NEC). Partnership with local SI is common entry path. Japanese-language support mandatory. Long relationship building."},
        "Netherlands": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "COO", "Head of Digital"], "entry_difficulty": "easy", "typical_deal_cycle": 50, "notes": "GDPR/AVG compliance. Dutch buyers are internationally oriented. Amsterdam tech hub has many international IT buyers. Strong cloud-first culture."},
        "Brazil": {"primary_buyer": "CIO / Diretor de TI", "secondary_buyers": ["CTO", "COO", "Head of Infrastructure"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "LGPD compliance. Portuguese materials required. São Paulo is IT hub. BNDES financing for large IT projects. Government needs SICAF registration for procurement."},
        "South Africa": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "COO", "IT Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "POPIA compliance. Strong cloud migration demand. Johannesburg financial district is primary IT market. Government SITA procurement process for public sector."},
        "Mexico": {"primary_buyer": "CIO / Director de TI", "secondary_buyers": ["CTO", "COO", "Head of Infrastructure"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "LFPDPPP privacy compliance. Spanish materials required. Nearshoring driving GCC setup demand. CompraNet for government procurement."},
        "Poland": {"primary_buyer": "CIO / Dyrektor IT", "secondary_buyers": ["CTO", "COO", "Head of IT"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "GDPR compliance. Strong IT outsourcing delivery hub. Warsaw and Krakow tech scenes. EU structural funds for digital transformation projects."},
    },
    "Fintech": {
        "USA": {"primary_buyer": "CFO / VP Finance", "secondary_buyers": ["CTO", "Head of Payments", "Chief Risk Officer"], "entry_difficulty": "hard", "typical_deal_cycle": 90, "notes": "FinCEN/BSA compliance required. State money transmitter licenses. SOC 2 Type II mandatory. SEC/CFTC for securities-adjacent. Long compliance review cycles."},
        "UK": {"primary_buyer": "CFO / Head of Finance", "secondary_buyers": ["CTO", "Chief Risk Officer", "Head of Compliance"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "FCA authorization or exemption required. PSD2/Open Banking opportunities. GDPR compliance. FCA sandbox available for new entrants. Strong investor ecosystem."},
        "Germany": {"primary_buyer": "CFO / Head of Finance", "secondary_buyers": ["CTO", "Compliance Officer", "Head of Treasury"], "entry_difficulty": "hard", "typical_deal_cycle": 120, "notes": "BaFin licensing or passporting required. Very conservative financial market. Deutsche Bank / Commerzbank slow to adopt new fintech. Sparkassen (savings banks) separate ecosystem."},
        "Singapore": {"primary_buyer": "CFO / Head of Finance", "secondary_buyers": ["CTO", "Head of Compliance", "CISO"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "MAS licensing (PS Act, SFA). MAS Fintech Sandbox available. Strong ASEAN expansion hub. Well-regulated, predictable environment. English-native financial sector."},
        "UAE": {"primary_buyer": "CFO / Head of Treasury", "secondary_buyers": ["CTO", "COO", "Head of Compliance"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "CBUAE or DFSA (DIFC) or FSRA (ADGM) licensing depending on entity. Crypto/digital asset regulation via VARA. Strong cross-border payment demand. Arabic language for retail-facing."},
        "India": {"primary_buyer": "CFO / VP Finance", "secondary_buyers": ["CTO", "Head of Compliance", "CEO"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "RBI licensing (PA, PG, NBFC etc). UPI integration is table stakes. PCI-DSS compliance. DPDP Act compliance. Large underbanked market creating opportunity. Price-sensitive."},
        "Nigeria": {"primary_buyer": "CFO / Head of Finance", "secondary_buyers": ["CEO", "CTO", "Head of Compliance"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "CBN licensing required. NIBSS integration for interbank. Strong mobile money and remittance demand. USD settlement preferred. Naira volatility complicates pricing."},
        "Kenya": {"primary_buyer": "CFO / Head of Finance", "secondary_buyers": ["CEO", "CTO", "Head of Compliance"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "CBK licensing. M-Pesa API integration is critical. Strong mobile money ecosystem. East Africa regional hub for fintech. Data Protection Act compliance."},
        "Australia": {"primary_buyer": "CFO / Head of Finance", "secondary_buyers": ["CTO", "Chief Risk Officer", "Head of Compliance"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "ASIC AFSL license required. CDR (Consumer Data Right) / Open Banking compliance. AUSTRAC AML obligations. NPP (New Payments Platform) integration preferred."},
        "Brazil": {"primary_buyer": "CFO / Diretor Financeiro", "secondary_buyers": ["CTO", "Head of Compliance", "CEO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Banco Central regulation. PIX integration mandatory. Open Finance Brazil compliance. LGPD for data. Strong fintech ecosystem (Nubank effect). Complex tax structure."},
        "Israel": {"primary_buyer": "CFO / VP Finance", "secondary_buyers": ["CTO", "CEO (startup)", "Head of Compliance"], "entry_difficulty": "medium", "typical_deal_cycle": 45, "notes": "Bank of Israel licensing for payment services. Strong fintech startup ecosystem. Fast technical decisions. IVC (Israel Venture Capital) ecosystem knowledge useful."},
        "Netherlands": {"primary_buyer": "CFO / Head of Finance", "secondary_buyers": ["CTO", "Compliance Officer", "Head of Treasury"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "DNB/AFM regulation. PSD2/SEPA compliance. Amsterdam is EU fintech hub. GDPR/AVG compliance. Strong cross-border payment infrastructure."},
        "South Africa": {"primary_buyer": "CFO / Head of Finance", "secondary_buyers": ["CTO", "Head of Compliance", "CEO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "SARB licensing for payment services. FICA (Financial Intelligence Centre Act) AML. POPIA compliance. Strong mobile banking demand. ZAR volatility affects pricing."},
        "Mexico": {"primary_buyer": "CFO / Director Financiero", "secondary_buyers": ["CTO", "Head of Compliance", "CEO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "CNBV / Banxico fintech law licensing. SPEI integration for domestic transfers. CFDI e-invoicing required. Anti-LAVADO (AML) compliance. Growing fintech market."},
        "Sweden": {"primary_buyer": "CFO / Head of Finance", "secondary_buyers": ["CTO", "Head of Compliance", "CEO"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Finansinspektionen regulation. Swish payments integration. BankID authentication. Strong cashless society — high fintech adoption. GDPR compliance. Klarna ecosystem influence."},
    },
    "Healthcare": {
        "USA": {"primary_buyer": "CIO / Chief Medical Information Officer", "secondary_buyers": ["CMO", "COO", "VP of Clinical Operations"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "HIPAA compliance mandatory. HL7/FHIR interoperability. FDA clearance for medical devices/SaMD. ONC certification for EHR. Long procurement through GPOs. Epic/Cerner dominance."},
        "UK": {"primary_buyer": "Chief Digital & Information Officer / CIO", "secondary_buyers": ["Medical Director", "COO", "Head of Digital"], "entry_difficulty": "hard", "typical_deal_cycle": "150", "notes": "NHS procurement through NHS Supply Chain or frameworks. DSP Toolkit compliance. DTAC assessment for digital health. MHRA for medical devices. Strong GP/primary care market."},
        "Germany": {"primary_buyer": "Klinikleitung / CIO", "secondary_buyers": ["Chefarzt (CMO)", "COO", "IT-Leiter"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "DSGVO (GDPR) + KHZG (hospital digitization fund) compliance. CE marking for medical devices. gematik TI infrastructure integration. Public hospital procurement slow."},
        "UAE": {"primary_buyer": "CEO / COO of Hospital Group", "secondary_buyers": ["CIO", "CMO", "Head of Digital Health"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "DHA (Dubai) / DOH (Abu Dhabi) / MOH licensing. NABIDH (Dubai health data) integration. Strong private hospital market. Medical tourism driving investment."},
        "India": {"primary_buyer": "Hospital CEO / CIO", "secondary_buyers": ["CMO", "COO", "Head of IT"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "ABDM (Ayushman Bharat Digital Mission) integration. CDSCO for medical devices. Apollo, Fortis, Max are major private chains. Price-sensitive — INR pricing. Telemedicine growing post-COVID."},
        "Singapore": {"primary_buyer": "CIO / Director of IT", "secondary_buyers": ["CEO", "CMO", "Head of Clinical Informatics"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "MOH Singapore compliance. NEHR (National EHR) integration. PDPA compliance. Private hospital market (Raffles, Mount Elizabeth) faster than public clusters."},
        "Australia": {"primary_buyer": "CIO / Head of Digital Health", "secondary_buyers": ["CEO", "CMO", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "My Health Record integration. TGA for medical devices. Privacy Act (Health Records). Medicare integration for billing. Strong telehealth demand. State vs federal health systems."},
        "Saudi Arabia": {"primary_buyer": "CEO / COO of Hospital", "secondary_buyers": ["CIO", "CMO", "Head of Digital Health"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "MOH Saudi Arabia licensing. CBAHI accreditation. Ehr mandate (Seha / NHC). Vision 2030 health transformation budget huge but procurement slow. Arabic language required."},
        "Brazil": {"primary_buyer": "Diretor Hospitalar / CIO", "secondary_buyers": ["CMO", "COO", "Head of TI"], "entry_difficulty": "medium", "typical_deal_cycle": 120, "notes": "ANVISA for medical devices. CFM medical ethics compliance. LGPD for patient data. Portuguese materials required. Private Unimed/Hapvida networks are major buyers."},
        "Nigeria": {"primary_buyer": "Hospital CEO / Head of IT", "secondary_buyers": ["CMO", "COO", "Administrator"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "NAFDAC for medical products. Private hospital chains growing fast. Telemedicine regulation emerging. Price-sensitive market — ROI proof needed."},
        "Japan": {"primary_buyer": "Hospital Administrator / CIO", "secondary_buyers": ["Chief Physician", "IT Manager", "COO"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "PMDA for medical devices. Very conservative — clinical evidence required. Japanese EMR ecosystem (ORCA) dominates primary care. Long relationship building before entry."},
        "South Africa": {"primary_buyer": "CEO / CIO of Hospital Group", "secondary_buyers": ["CMO", "COO", "Head of IT"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "HPCSA and DOH compliance. POPIA for patient data. Private networks (Mediclinic, Netcare, Life Healthcare) are primary buyers. NHI reform creating new public sector demand."},
    },
    "Retail/Ecommerce": {
        "USA": {"primary_buyer": "VP of Ecommerce / CMO", "secondary_buyers": ["CTO", "Head of Digital", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 45, "notes": "Shopify/BigCommerce ecosystem. Strong DTC brand culture. Amazon Marketplace integration key. CCPA compliance. Fast decisions for martech stack additions."},
        "UK": {"primary_buyer": "Head of Ecommerce / Digital Director", "secondary_buyers": ["CMO", "CTO", "COO"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "GDPR + ICO compliance. Strong omnichannel retail. Royal Mail and DPD integration for delivery. VAT and HMRC compliance for cross-border."},
        "Germany": {"primary_buyer": "E-Commerce Manager / Head of Digital", "secondary_buyers": ["CMO", "CTO", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Sehr strict consumer protection laws (Widerrufsrecht). UStID (VAT ID) and DSGVO compliance. Strong preference for DHL, Hermes, DPD delivery. Trusted Shops certification builds trust."},
        "UAE": {"primary_buyer": "Head of Ecommerce / Digital Director", "secondary_buyers": ["CEO", "CMO", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Noon and Amazon.ae marketplace integration. Cash on delivery still significant. Ramadan season planning important. Arabic storefront for broader reach."},
        "India": {"primary_buyer": "VP Ecommerce / Head of Digital", "secondary_buyers": ["CMO", "CTO", "CEO (D2C startup)"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Flipkart/Amazon/Meesho marketplace integration. UPI payments table stakes. GST compliance and e-invoicing. Vernacular language support for Tier 2/3. Quick commerce growing."},
        "Singapore": {"primary_buyer": "Head of Ecommerce / CMO", "secondary_buyers": ["CTO", "COO", "Head of Digital"], "entry_difficulty": "easy", "typical_deal_cycle": 40, "notes": "Lazada/Shopee ecosystem. Strong mobile commerce. PDPA compliance. Social commerce through Instagram/TikTok growing. APAC HQ decisions often made in Singapore."},
        "Japan": {"primary_buyer": "EC部長 (Ecommerce Manager) / CMO", "secondary_buyers": ["CTO", "COO", "Head of Digital Marketing"], "entry_difficulty": "hard", "typical_deal_cycle": 120, "notes": "Rakuten ecosystem dominance. Japanese-language storefront mandatory. Very high product photography standards. Convenience store payment options required. COD still common."},
        "Brazil": {"primary_buyer": "Diretor de E-commerce / CMO", "secondary_buyers": ["CTO", "COO", "Head of Marketing Digital"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Mercado Libre dominance. Boleto bancário + PIX payments required. LGPD compliance. Nota Fiscal for all sales. Portuguese storefront. Installments (parcelas) culture."},
        "Indonesia": {"primary_buyer": "Head of Ecommerce / CMO", "secondary_buyers": ["CTO", "CEO (startup)", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Tokopedia/Shopee ecosystem. GOjek/GrabFood integration for quick commerce. CoD still significant. PDP Law compliance. Bahasa Indonesia content required."},
        "Australia": {"primary_buyer": "Head of Ecommerce / Digital Director", "secondary_buyers": ["CMO", "CTO", "COO"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "Privacy Act compliance. Australia Post integration standard. Buy Now Pay Later (Afterpay) integration expected. ACCC consumer law compliance. Strong social commerce."},
        "Saudi Arabia": {"primary_buyer": "Head of Digital / Ecommerce Manager", "secondary_buyers": ["CMO", "CEO (SME)", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Noon.com and Amazon.sa marketplace. SFDA for food/health products. ZATCA e-invoicing required. Arabic storefront mandatory. High mobile commerce adoption."},
        "Mexico": {"primary_buyer": "Director de Ecommerce / CMO", "secondary_buyers": ["CTO", "COO", "Head of Digital"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "MercadoLibre ecosystem. OXXO Pay and SPEI payment methods. CFDI invoicing compliance. Spanish storefront. PROFECO consumer protection compliance."},
        "South Africa": {"primary_buyer": "Head of Ecommerce / Digital Director", "secondary_buyers": ["CMO", "CTO", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "POPIA compliance. Takealot marketplace dominant. EFT and SnapScan payment preferences. Strong mobile commerce. ECT Act for online contracts."},
        "Turkey": {"primary_buyer": "E-ticaret Müdürü / CMO", "secondary_buyers": ["CTO", "COO", "CEO (SME)"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Trendyol and Hepsiburada ecosystems. Turkish-language storefront required. KVKK compliance. EFT/EFT payments. Strong fast fashion and lifestyle e-commerce."},
    },
    "Education": {
        "USA": {"primary_buyer": "CIO / Head of EdTech", "secondary_buyers": ["Superintendent", "VP Academic Affairs", "Provost"], "entry_difficulty": "medium", "typical_deal_cycle": 120, "notes": "FERPA compliance mandatory. State procurement contracts (e.g., PEPPM). K-12 vs Higher Ed are very different buyers. Title funding for underserved districts."},
        "UK": {"primary_buyer": "Head of IT / Vice Principal Digital", "secondary_buyers": ["Principal", "CIO", "Head of Academic Affairs"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "GDPR + UK GDPR compliance. DfE (Dept for Education) compliance. ESFA funding rules for FE. HESA data reporting for HE. Academies Trust procurement varies."},
        "India": {"primary_buyer": "Principal / Head of IT", "secondary_buyers": ["Trustee (private schools)", "CIO", "VP Academics"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "NEP 2020 digital mandate. CBSE and state board alignment required. EdTech regulation emerging. Strong demand in K-12 private and coaching. DPDP compliance for student data."},
        "UAE": {"primary_buyer": "KHDA-registered School Principal / CIO", "secondary_buyers": ["CEO (ed group)", "Head of Digital", "Academic Director"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "KHDA (Dubai) / ADEK (Abu Dhabi) compliance. Arabic and English bilingual content. Large private school market. University districts growing (Dubai Knowledge Park)."},
        "Singapore": {"primary_buyer": "Head of IT / Principal", "secondary_buyers": ["MOE Official", "CIO", "VP Academic"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "MOE Singapore compliance. PDPA for student data. Strong international school market. EdTech funded by SkillsFuture program. High parental engagement in buying."},
        "Germany": {"primary_buyer": "Schulleiter (Principal) / IT-Koordinator", "secondary_buyers": ["KMK representative", "CIO (university)", "VHS Director"], "entry_difficulty": "hard", "typical_deal_cycle": 120, "notes": "State (Länder) education authority approval required. DSGVO for student data. Public schools are slow procurement. Strong vocational (Berufsschule) market. Open source preference."},
        "Brazil": {"primary_buyer": "Diretor Escolar / CIO", "secondary_buyers": ["Reitor (university)", "Head of TI", "Coordenador Pedagógico"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "LGPD for student data. Portuguese materials required. Private Cogna/Ânima university groups are major buyers. FNDE funding for public schools. Strong EAD (distance learning) market."},
        "Australia": {"primary_buyer": "Principal / Head of IT", "secondary_buyers": ["CIO", "Deputy Principal", "Head of Digital Learning"], "entry_difficulty": "easy", "typical_deal_cycle": 75, "notes": "Privacy Act (student data). ACARA curriculum alignment. State vs federal funding complexity. Strong iPad/Chromebook device ecosystem. NAPLAN digital assessment driver."},
        "Nigeria": {"primary_buyer": "School Proprietor / Head of IT", "secondary_buyers": ["Principal", "CEO (ed chain)", "IT Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Private schools growing fast. WAEC/NECO exam preparation demand. Mobile learning for rural areas. Low infrastructure — offline-capable tools valued."},
        "Indonesia": {"primary_buyer": "Kepala Sekolah (Principal) / IT Manager", "secondary_buyers": ["CEO (edu chain)", "Head of Digital", "Diknas official"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Kemendikbud compliance. Bahasa Indonesia materials. Government Merdeka Belajar curriculum. Strong private tutoring (bimbel) market. Mobile-first EdTech."},
        "Vietnam": {"primary_buyer": "School Director / IT Manager", "secondary_buyers": ["CEO (private chain)", "Academic Director", "MOE official"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "MOET compliance. Vietnamese-language content. Growing private K-12 market. English learning apps strong. Government digital education investment post-COVID."},
        "South Africa": {"primary_buyer": "Principal / Head of IT", "secondary_buyers": ["CEO (private chain)", "CIO", "Head of Digital Learning"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "POPIA for student data. CAPS curriculum alignment. DBE (Dept Basic Education) for public. Strong private school market. Mobile data costs affect digital adoption."},
    },
    "Legal": {
        "USA": {"primary_buyer": "Managing Partner / COO", "secondary_buyers": ["CIO", "IT Director", "Chief Knowledge Officer"], "entry_difficulty": "hard", "typical_deal_cycle": 120, "notes": "ABA ethics compliance for legal tech. SOC 2 Type II required. Attorney-client privilege data handling critical. Am Law 100 firms have dedicated procurement. Hourly billing model impacts ROI pitch."},
        "UK": {"primary_buyer": "Managing Partner / Practice Manager", "secondary_buyers": ["CIO", "Head of IT", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "SRA (Solicitors Regulation Authority) compliance. GDPR for client data. Magic Circle and Silver Circle have enterprise buying. High Street firms buy via referral. Lexcel accreditation."},
        "Germany": {"primary_buyer": "Geschäftsführer (Managing Partner) / IT-Leiter", "secondary_buyers": ["Partner", "Kanzleimanager", "CIO"], "entry_difficulty": "hard", "typical_deal_cycle": 150, "notes": "BRAO (federal lawyers' act) compliance. DSGVO for client data. beA (certified electronic mailbox) integration required. Very conservative — long evaluation cycles."},
        "UAE": {"primary_buyer": "Managing Partner / COO", "secondary_buyers": ["Head of IT", "CEO (legal firm)", "Practice Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "DIFC / ADGM law firm regulations. Arabic and English bilingual required. Strong international arbitration market. Government-adjacent work requires Emirati ownership."},
        "India": {"primary_buyer": "Senior Partner / IT Head", "secondary_buyers": ["Managing Partner", "CEO (legal startup)", "COO"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "Bar Council compliance. Indian tech law stack (Contract Act, IT Act). Strong LegalTech startup ecosystem. DPDP Act for client data. Price-sensitive — INR pricing."},
        "Singapore": {"primary_buyer": "Managing Partner / COO", "secondary_buyers": ["CIO", "Head of IT", "Practice Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "SAL/LLB qualified staff. PDPA for client data. Strong international arbitration (SIAC). English common law base. Tech-forward bar association."},
        "Australia": {"primary_buyer": "Managing Partner / Practice Manager", "secondary_buyers": ["CIO", "COO", "Head of IT"], "entry_difficulty": "easy", "typical_deal_cycle": 75, "notes": "Legal Services Commission compliance. Privacy Act for client data. Strong national law firm market (MinterEllison, Allens). NSW/VIC law society rules."},
        "Netherlands": {"primary_buyer": "Managing Partner / Office Manager", "secondary_buyers": ["IT Manager", "COO", "Head of Knowledge Management"], "entry_difficulty": "easy", "typical_deal_cycle": 75, "notes": "NOvA (Dutch Bar) compliance. GDPR/AVG for client data. Amsterdam and Rotterdam legal markets. Strong international arbitration and trade law demand."},
        "Brazil": {"primary_buyer": "Sócio-Gerente (Managing Partner) / COO", "secondary_buyers": ["CIO", "Head of TI", "Administrador"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "OAB (Brazilian Bar) compliance. LGPD for client data. Portuguese materials required. PJe (court system) integration important. São Paulo legal market very large."},
        "Israel": {"primary_buyer": "Managing Partner / COO", "secondary_buyers": ["IT Manager", "Head of Knowledge", "CEO (legal tech)"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "Israel Bar Association compliance. Privacy Protection Law for client data. Strong tech law and IP practices. Fast decisions. English widely used in international firms."},
        "Canada": {"primary_buyer": "Managing Partner / CIO", "secondary_buyers": ["COO", "Head of IT", "Knowledge Management Director"], "entry_difficulty": "easy", "typical_deal_cycle": 75, "notes": "Law Society compliance (varies by province). PIPEDA/Quebec Bill 64. French requirement in Quebec. Strong Bay Street (Toronto) legal market."},
        "South Africa": {"primary_buyer": "Managing Partner / Practice Manager", "secondary_buyers": ["Head of IT", "COO", "Knowledge Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "LSSA (Law Society) compliance. POPIA for client data. Johannesburg and Cape Town legal hubs. English and Afrikaans markets. BEE (B-BBEE) considerations for partnerships."},
    },
    "Construction": {
        "USA": {"primary_buyer": "VP of Operations / COO", "secondary_buyers": ["Project Director", "Head of IT", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Procore/Autodesk ecosystem dominance. OSHA safety compliance. Prevailing wage requirements for government contracts. Strong BIM adoption in large firms."},
        "UK": {"primary_buyer": "Operations Director / Project Director", "secondary_buyers": ["COO", "Head of IT", "BIM Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "BIM Level 2/3 compliance for government projects. CDM Regulations safety compliance. RICS certification respected. Groundworks and civil engineering separate from building."},
        "Germany": {"primary_buyer": "Projektleiter / Geschäftsführer", "secondary_buyers": ["Bauleiter", "COO", "IT-Leiter"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "VOB (construction contract regulations) compliance. DIN standards for materials. BIM adoption growing with EU mandate. GU (general contractor) vs specialist subcontractors."},
        "UAE": {"primary_buyer": "Project Director / COO", "secondary_buyers": ["CEO", "Head of Operations", "BIM Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "Dubai Municipality / DDA approvals. Expo legacy projects. Strong mega-project pipeline (Vision 2030 in Saudi adjacent). Arabic and English bilingual required."},
        "India": {"primary_buyer": "MD / COO", "secondary_buyers": ["Project Manager", "Head of Operations", "CFO"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "RERA compliance for real estate construction. IS code compliance. Strong infra spend (PM Gati Shakti). Price-sensitive. L1 bidding for government projects. CPWD standards."},
        "Saudi Arabia": {"primary_buyer": "Project Director / COO", "secondary_buyers": ["CEO", "Head of Operations", "Contract Manager"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "MOMRA/NEOM project framework. Saudi Aramco SAP-based procurement for energy construction. Arabic required. Baladiya (municipality) permits. Vision 2030 NEOM and Red Sea Project budgets enormous."},
        "Australia": {"primary_buyer": "Project Director / COO", "secondary_buyers": ["Operations Manager", "Head of IT", "CFO"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "WHS (Work Health and Safety) Act compliance. NCC (National Construction Code). Strong infrastructure pipeline. State government procurement varies. BIM adoption growing."},
        "Singapore": {"primary_buyer": "Project Director / COO", "secondary_buyers": ["BIM Manager", "Head of IT", "CEO (SME builder)"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "BCA (Building and Construction Authority) compliance. CORENET e-submission. BIM mandated for public projects. Green Mark certification growing. Limited land = vertical construction expertise valued."},
        "Nigeria": {"primary_buyer": "MD / Project Manager", "secondary_buyers": ["COO", "Head of Operations", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "COREN registration required. NIS standards. Oil & gas construction separate ecosystem. Lagos and Abuja primary markets. Generator/power backup integration expected."},
        "Brazil": {"primary_buyer": "Diretor de Obras / COO", "secondary_buyers": ["MD", "Gerente de Projetos", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "CREA/CAU engineering registration. ABNT standards. Minha Casa Minha Vida program for affordable housing. São Paulo and Rio primary markets. SPED accounting integration."},
        "Indonesia": {"primary_buyer": "Project Director / COO", "secondary_buyers": ["Direktur", "Head of Operations", "Manager Proyek"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Kementerian PUPR compliance. SNI standards. National Strategic Projects (PSN). BPJS Ketenagakerjaan for worker coverage. Jakarta and new capital (IKN) development."},
        "Turkey": {"primary_buyer": "Proje Direktörü / COO", "secondary_buyers": ["Genel Müdür (GM)", "Head of Operations", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "İMO (Chamber of Civil Engineers) compliance. Earthquake resistance standards critical. Strong construction export (Turkish contractors global). Istanbul mega-projects ongoing."},
    },
    "Food & Beverage": {
        "USA": {"primary_buyer": "VP of Operations / COO", "secondary_buyers": ["Head of Supply Chain", "CFO", "VP of Sales"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "FDA FSMA compliance. USDA for meat/poultry. GFSI certification (SQF, BRC). Strong cold chain and DSD (Direct Store Delivery) requirements. Whole Foods/Amazon/Walmart buyer requirements."},
        "UK": {"primary_buyer": "Operations Director / Supply Chain Director", "secondary_buyers": ["COO", "Head of Procurement", "Quality Director"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "FSA (Food Standards Agency) compliance. BRCGS certification. Tesco/Sainsbury's supplier code of practice. Post-Brexit food labelling changes. Strong organic and free-from market."},
        "Germany": {"primary_buyer": "Operations Manager / COO", "secondary_buyers": ["Qualitätsmanager", "Head of Supply Chain", "Einkaufsleiter"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "BVL food safety compliance. LMIV food labelling regulation. IFS Food certification. EDEKA/REWE supplier requirements strict. Strong organic (Bio) and fair trade market."},
        "UAE": {"primary_buyer": "COO / Operations Director", "secondary_buyers": ["CEO", "Head of Supply Chain", "Quality Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "ESMA/Dubai Municipality food safety. Halal certification mandatory. HACCP compliance. Strong F&B import market. Ramadan/Eid demand planning important."},
        "India": {"primary_buyer": "MD / Head of Operations", "secondary_buyers": ["COO", "Plant Manager", "Head of Supply Chain"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "FSSAI licensing mandatory. BIS standards for processed food. GST on food categories. Strong FMCG market (Hindustan Unilever, Nestle model). Cold chain infrastructure developing."},
        "Japan": {"primary_buyer": "部長 (Division Head) / Operations Manager", "secondary_buyers": ["COO", "Quality Manager", "Head of Supply Chain"], "entry_difficulty": "hard", "typical_deal_cycle": 150, "notes": "Extremely high food safety standards. JAS (Japan Agricultural Standards). Strict labelling laws. Shelf life expectations very precise. Japanese consumer expectations are unforgiving — quality is paramount."},
        "Singapore": {"primary_buyer": "COO / Head of Operations", "secondary_buyers": ["CEO (F&B chain)", "Supply Chain Manager", "Quality Manager"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "SFA (Singapore Food Agency) compliance. HACCP required. Strong hawker culture digitization demand. F&B tech adoption fast. Regional distribution hub for ASEAN."},
        "Australia": {"primary_buyer": "COO / Operations Manager", "secondary_buyers": ["Head of Supply Chain", "Quality Director", "CEO (SME)"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "FSANZ (Food Standards Australia NZ) compliance. Country of origin labelling. Woolworths/Coles supplier standards. Strong export market (beef, wine, dairy)."},
        "Brazil": {"primary_buyer": "Diretor de Operações / COO", "secondary_buyers": ["Gerente de Qualidade", "Head of Supply Chain", "CEO (SME)"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "ANVISA food safety compliance. Nota Fiscal for all transactions. LGPD for consumer data. Strong Ambev/JBS model. Supermarket retail: Grupo Pão de Açúcar, Carrefour Brazil."},
        "Mexico": {"primary_buyer": "Director de Operaciones / COO", "secondary_buyers": ["Gerente de Calidad", "Head of Supply Chain", "CEO (SME)"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "COFEPRIS food safety. NOM standards for food labeling. Oxxo and FEMSA retail ecosystem. Strong Bimbo/Sigma group model. USMCA certification for export."},
        "Nigeria": {"primary_buyer": "CEO / COO", "secondary_buyers": ["Head of Operations", "Quality Manager", "Supply Chain Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "NAFDAC registration required. SON standards. Halal certification for Muslim-majority market. Cold chain infrastructure limited — ambient products preferred. Strong informal distribution."},
        "Indonesia": {"primary_buyer": "Direktur Operasi / COO", "secondary_buyers": ["CEO (FMCG)", "Quality Manager", "Head of Supply Chain"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "BPOM (food safety authority) compliance. Halal MUI certification mandatory. SNI standards. Indomaret/Alfamart retail chains. Strong Indofood/ABC ecosystem model."},
        "South Africa": {"primary_buyer": "COO / Operations Manager", "secondary_buyers": ["Head of Supply Chain", "Quality Director", "CEO (SME)"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "DFFE/DALRRD compliance for food safety. Woolworths SA and Checkers supplier standards. BEE preferential procurement. Strong wine and fruit export market."},
        "Vietnam": {"primary_buyer": "Giám đốc Vận hành / COO", "secondary_buyers": ["CEO", "Quality Manager", "Supply Chain Manager"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "MARD and MOIT food safety regulations. Growing consumer food market. Halal certification for Muslim ASEAN export. Cold chain rapidly developing. VinCommerce retail ecosystem."},
    },
    "Real Estate": {
        "USA": {"primary_buyer": "VP of Technology / COO", "secondary_buyers": ["CIO", "Head of Digital", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "NAR (National Association of Realtors) compliance. MLS (Multiple Listing Service) integration required. RESPA/TRID compliance for transactions. Strong PropTech adoption."},
        "UK": {"primary_buyer": "Head of Technology / Operations Director", "secondary_buyers": ["COO", "CIO", "Head of Digital"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "RICS (Royal Institution of Chartered Surveyors) standards. GDPR compliance. Rightmove/Zoopla portal integration. Anti-money laundering (AML) for agents. HMRC SDLT reporting."},
        "UAE": {"primary_buyer": "CEO / COO", "secondary_buyers": ["Head of Digital", "Sales Director", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "RERA (Real Estate Regulatory Agency) Dubai compliance. DLD (Dubai Land Department) integration. Bayut/Property Finder portal integration. Off-plan regulation requirements."},
        "India": {"primary_buyer": "MD / Head of Technology", "secondary_buyers": ["COO", "Head of Sales", "CFO"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "RERA compliance (state-wise). MahaRERA for Maharashtra. GST on under-construction properties. Strong PropTech adoption in Mumbai/Bengaluru/Hyderabad. 99acres/MagicBricks portal integration."},
        "Singapore": {"primary_buyer": "CEO / COO", "secondary_buyers": ["Head of Technology", "CFO", "Sales Director"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "CEA (Council for Estate Agencies) compliance. PropertyGuru portal integration. PDPA for buyer/tenant data. Additional Buyer's Stamp Duty considerations. Limited land = complex valuation."},
        "Germany": {"primary_buyer": "Geschäftsführer / Immobilienverwalter", "secondary_buyers": ["COO", "IT-Leiter", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "MaBV (real estate broker regulation) compliance. Grundbuch (land registry) integration. DSGVO for client data. IVD (real estate association) standards. Energy performance certificate (EPC) requirements."},
        "Australia": {"primary_buyer": "CEO / COO", "secondary_buyers": ["Head of Technology", "Head of Operations", "CFO"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "State-based licensing requirements. Domain/REA portal integration. Privacy Act for client data. Foreign investment review (FIRB) for international buyers. Strong property management software market."},
        "Saudi Arabia": {"primary_buyer": "CEO / Head of Operations", "secondary_buyers": ["COO", "Head of Digital", "CFO"], "entry_difficulty": "hard", "typical_deal_cycle": 150, "notes": "REGA (Real Estate General Authority) compliance. Wafi off-plan project regulation. Absher integration for property transactions. Ejar platform for rental registration. Vision 2030 NEOM mega-project."},
        "Brazil": {"primary_buyer": "Diretor Geral / COO", "secondary_buyers": ["Head of TI", "CFO", "Gerente Comercial"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "CRECI (regional council) compliance. IGPM index for rental contracts. Cartório (registry office) integration. ZAP Imóveis/VivaReal portal. Leilão (auction) market growing."},
        "Nigeria": {"primary_buyer": "CEO / COO", "secondary_buyers": ["Head of IT", "Sales Director", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "LASRERA (Lagos) compliance. C of O (Certificate of Occupancy) verification. PropertyPro/Private Property portal. FHA (Federal Housing Authority) for affordable housing. Title verification critical."},
        "Mexico": {"primary_buyer": "Director General / COO", "secondary_buyers": ["Head of TI", "Gerente de Ventas", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "PROFECO consumer protection. Inmuebles24/Lamudi portal integration. SAT (tax) compliance for transactions. Fideicomiso (bank trust) for foreign buyers. Mexico City main market."},
        "Turkey": {"primary_buyer": "Genel Müdür (GM) / COO", "secondary_buyers": ["Head of IT", "Satış Müdürü", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "TKGM (land registry) integration. Sahibinden portal integration. KVKK for client data. Citizenship by investment program attracting international buyers. Istanbul and Antalya primary markets."},
        "Poland": {"primary_buyer": "CEO / COO", "secondary_buyers": ["Head of IT", "Sales Director", "CFO"], "entry_difficulty": "easy", "typical_deal_cycle": 75, "notes": "PFRN (real estate agent federation) standards. GDPR compliance. Otodom/OLX portal. KRS registration for developers. EU structural funds for housing. Warsaw main market."},
    },
    "Media/Publishing": {
        "USA": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "VP of Product", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "CCPA compliance. Strong digital-first transformation pressure. Paywall and subscription management critical. Ad tech ecosystem (DV360, TTD) integration. First-party data strategy in post-cookie world."},
        "UK": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "Chief Digital Officer", "COO"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "ICO/GDPR compliance. IPSO (press standards) for news. BBC iPlayer ecosystem. Strong podcast and streaming market. NRS (readership survey) integration valued."},
        "Germany": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "Chefredakteur (Editor-in-Chief)", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "DSGVO compliance. Leistungsschutzrecht (press publisher right) compliance. ARD/ZDF public media ecosystem. VDZ (magazine publishers) standards. Very privacy-conscious audience."},
        "India": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "CEO (digital media)", "Head of Product"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "IT Act compliance. MIB (Ministry I&B) for broadcasting. Strong regional language content demand. JioCinema/Hotstar ecosystem. Price-sensitive subscription models."},
        "Australia": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "CEO", "Head of Data"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "ACMA (media regulator) compliance. Privacy Act for subscriber data. News Media Bargaining Code (NMBC) awareness. Strong ABC/commercial TV ecosystem. Streaming first mentality."},
        "Netherlands": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "CEO", "Chief Data Officer"], "entry_difficulty": "easy", "typical_deal_cycle": 60, "notes": "GDPR/AVG compliance. DPA (Data Protection Authority) active enforcement. English-language tech publishers strong. Strong quality journalism tradition."},
        "France": {"primary_buyer": "Directeur Technique / CTO", "secondary_buyers": ["CMO", "Directeur Digital", "CEO"], "entry_difficulty": "hard", "typical_deal_cycle": 120, "notes": "CNIL (data regulator) very strict enforcement. ARCOM (media regulator). French-language content mandatory. Droit d'auteur (copyright) culture. Le Monde/Le Figaro ecosystem."},
        "Brazil": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "CEO", "Head of Produto"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "LGPD compliance. Portuguese content. ANATEL for broadcasting. Globo ecosystem dominance. WhatsApp-driven content distribution. Strong news subscription growth."},
        "Singapore": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "CEO", "Chief Digital Officer"], "entry_difficulty": "easy", "typical_deal_cycle": 45, "notes": "MDA (media authority) compliance. PDPA for subscriber data. IMDA for digital media. SPH (Singapore Press Holdings) ecosystem. Strong ASEAN regional media hub."},
        "South Africa": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "CEO", "Head of Product"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "POPIA compliance. ICASA (communications regulator). Naspers/Media24 ecosystem. Strong radio and TV consumption. Growing digital-native media startups."},
        "Nigeria": {"primary_buyer": "CEO / Head of Digital", "secondary_buyers": ["CMO", "CTO", "Head of Partnerships"], "entry_difficulty": "medium", "typical_deal_cycle": 60, "notes": "NBC (broadcast regulator) compliance. NDPR for user data. Strong Nollywood content market. Mobile-first consumption. Strong podcast and YouTube culture."},
        "Japan": {"primary_buyer": "CTO / Head of Digital", "secondary_buyers": ["CMO", "Managing Editor", "COO"], "entry_difficulty": "hard", "typical_deal_cycle": 150, "notes": "Strict copyright (Chosakuken-ho) enforcement. Japanese-language content mandatory. NHK public broadcast ecosystem. Manga/anime IP very protected. LINE ecosystem integration."},
    },
    "Pharma": {
        "USA": {"primary_buyer": "CIO / VP of IT", "secondary_buyers": ["CTO", "Head of Digital Health", "Chief Compliance Officer"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "FDA 21 CFR Part 11 compliance for electronic records. GxP validation required. SOC 2 + HIPAA. IQVIA/Veeva ecosystem dominance. Drug supply chain traceability (DSCSA) mandatory."},
        "UK": {"primary_buyer": "Head of IT / CIO", "secondary_buyers": ["CTO", "Quality Director", "Head of Digital"], "entry_difficulty": "hard", "typical_deal_cycle": 150, "notes": "MHRA compliance. GxP validation. GDP (Good Distribution Practice). NICE technology appraisal awareness. NHS procurement routes. Serialization requirements (FMD)."},
        "Germany": {"primary_buyer": "CIO / IT-Leiter", "secondary_buyers": ["CTO", "Compliance Officer", "Head of Digital"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "BfArM and EMA compliance. AMG (Pharmaceuticals Act). AMNOG pricing approval process. DSGVO. Serialization (FMD) mandatory. Very conservative procurement."},
        "India": {"primary_buyer": "IT Head / CIO", "secondary_buyers": ["CTO", "Head of Quality", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 75, "notes": "CDSCO compliance. Schedule M GMP standards. DPDP Act for patient data. India Pharma is massive API exporter. Price-sensitive but scale huge. Strong generic pharma focus."},
        "UAE": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["COO", "Head of Quality", "CEO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "MOH UAE and DHA Dubai compliance. Halal pharmaceutical certification. SFDA (Saudi) for cross-border distribution. Serialization requirements. Strong medical tourism driving pharma demand."},
        "Japan": {"primary_buyer": "IT部長 / CIO", "secondary_buyers": ["CTO", "Quality Manager", "Compliance Officer"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "PMDA compliance. GPSP/GVSP pharmacovigilance. Japanese-language mandatory. Very conservative — lengthy validation cycles. Local partner (Shigakkai, JPIA) relationships important."},
        "Brazil": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "Diretor de Qualidade", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 120, "notes": "ANVISA compliance. GxP validation. RDC regulations. LGPD for clinical/patient data. CONITEC for health tech assessment. Complex tax structure for pharma."},
        "Australia": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "Quality Director", "Head of Digital Health"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "TGA (Therapeutic Goods Administration) compliance. GMP/GDP certification. Serialization requirements. PBS (Pharmaceutical Benefits Scheme) listing process. Privacy Act."},
        "Singapore": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "Quality Director", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "HSA (Health Sciences Authority) compliance. GxP validation. Strong ASEAN regulatory hub. PDPA compliance. Biomedical Hub with A*STAR ecosystem."},
        "Netherlands": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "Quality Director", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "EMA (European Medicines Agency) HQ in Amsterdam. EMA compliance critical. GDPR/AVG. Netherlands is major pharma port hub (Breda, Rotterdam). GMP validation required."},
        "Canada": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "Quality Director", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Health Canada compliance. GxP validation. PIPEDA for health data. Quebec French bilingual requirements. Strong Ontario/Quebec pharma manufacturing base."},
        "South Africa": {"primary_buyer": "CIO / Head of IT", "secondary_buyers": ["CTO", "Quality Manager", "COO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "SAHPRA (Medicines regulator) compliance. GxP validation. POPIA for patient data. Strong generic pharma market. SADC regional hub for pharma distribution."},
    },
    "Clean Energy": {
        "USA": {"primary_buyer": "VP of Operations / COO", "secondary_buyers": ["CTO", "Head of Asset Management", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "IRA (Inflation Reduction Act) incentives driving huge investment. NERC CIP for grid cybersecurity. FERC compliance. Strong utility-scale solar, wind, and storage market. PJM/MISO/ERCOT ISO integration."},
        "UK": {"primary_buyer": "COO / Head of Operations", "secondary_buyers": ["CTO", "CFO", "Head of Asset Management"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "Ofgem regulation. CfD (Contracts for Difference) compliance. BEIS Net Zero targets. National Grid ESO integration. Strong offshore wind market."},
        "Germany": {"primary_buyer": "COO / Geschäftsführer", "secondary_buyers": ["CTO", "Head of Asset Management", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 120, "notes": "Bundesnetzagentur (BNetzA) regulation. EEG (Renewable Energy Sources Act). ENTSO-E grid compliance. Energiewende policy framework. Strong wind and solar market."},
        "UAE": {"primary_buyer": "CEO / COO", "secondary_buyers": ["CTO", "Head of Projects", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "DEWA and ADNOC renewable mandates. IRENA headquartered in Abu Dhabi. Masdar City / Mohammed bin Rashid Solar Park ecosystem. Net Zero 2050 government commitment. Arabic required for gov."},
        "India": {"primary_buyer": "Head of Projects / COO", "secondary_buyers": ["CTO", "CFO", "MD"], "entry_difficulty": "easy", "typical_deal_cycle": 75, "notes": "MNRE (Ministry of New and Renewable Energy) compliance. CEA and CERC for grid. 500GW renewable target by 2030. Price-sensitive market — LCOE focus. Adani/Tata ecosystem dominant."},
        "Saudi Arabia": {"primary_buyer": "COO / Head of Projects", "secondary_buyers": ["CEO", "CFO", "CTO"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "Saudi Vision 2030 — NEOM and 50% renewable target. REPDO (renewable procurement) compliance. ARAMCO energy transition involvement. Arabic required. Massive scale opportunities."},
        "Australia": {"primary_buyer": "COO / Head of Asset Management", "secondary_buyers": ["CTO", "CFO", "Head of Projects"], "entry_difficulty": "easy", "typical_deal_cycle": 75, "notes": "AEMO and AER regulation. Safeguard Mechanism compliance. Strong rooftop solar and large-scale storage pipeline. State government renewable targets vary. CEC (Clean Energy Council) membership."},
        "Netherlands": {"primary_buyer": "COO / Head of Operations", "secondary_buyers": ["CTO", "CFO", "Head of Projects"], "entry_difficulty": "easy", "typical_deal_cycle": 75, "notes": "ACM (regulatory authority). SDE++ subsidy scheme. Offshore wind leader (North Sea). European Green Deal alignment. Strong hydrogen economy investment."},
        "Japan": {"primary_buyer": "部長 / COO", "secondary_buyers": ["CTO", "Head of Projects", "CFO"], "entry_difficulty": "hard", "typical_deal_cycle": 180, "notes": "METI (energy ministry) compliance. FIT/FIP scheme compliance. Offshore wind development regulations. Nuclear phase-out creating renewable opportunity. Conservative procurement."},
        "Brazil": {"primary_buyer": "Diretor de Operações / COO", "secondary_buyers": ["CTO", "CFO", "Head of Projects"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "ANEEL (energy regulator) compliance. CCEE electricity trading compliance. Strong hydropower + wind + solar mix. Portuguese materials required. BNDES green financing available."},
        "South Africa": {"primary_buyer": "Head of Projects / COO", "secondary_buyers": ["CEO", "CTO", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "NERSA regulation. REIPPPP (renewable procurement) program. Loadshedding crisis creating urgency. IPP (Independent Power Producer) market. BBBEE requirements for project compliance."},
        "Germany": {"primary_buyer": "COO / Geschäftsführer", "secondary_buyers": ["CTO", "Head of Asset Management", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 120, "notes": "BNetzA regulation. EEG Renewable Energy Act. ENTSO-E grid compliance. Energiewende policy driving investment. Strong wind and solar market. Hydrogen strategy investment growing."},
        "Chile": {"primary_buyer": "COO / Head of Projects", "secondary_buyers": ["CEO", "CTO", "CFO"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "CNE and SEC regulation. Atacama Desert — best solar resource globally. Strong copper mining energy demand. ACERA (renewable association) membership. Green hydrogen export ambitions."},
        "Vietnam": {"primary_buyer": "Head of Projects / COO", "secondary_buyers": ["CEO", "CTO", "Director"], "entry_difficulty": "medium", "typical_deal_cycle": 90, "notes": "MOIT (energy ministry) compliance. FIT program regulations. Rapid solar buildout. Grid constraint challenges. EVN (state utility) is primary offtaker. Foreign investment approval required."},
    },
}

# Default buyer profile for any missing combo
DEFAULT_BUYER = {
    "primary_buyer": "COO / Head of Operations",
    "secondary_buyers": ["CEO", "CTO", "CFO"],
    "entry_difficulty": "medium",
    "typical_deal_cycle": 75,
    "notes": "No specific data for this combination. Default B2B entry: target the COO or CEO for SME, CIO/CTO for enterprise. Research local regulations before outreach.",
}

INDUSTRIES = sorted(BUYER_MAP.keys())
ALL_COUNTRIES = sorted({country for ind_data in BUYER_MAP.values() for country in ind_data.keys()})


@buyer_map_router.get("")
async def get_buyer_map(
    industry: str = Query(..., description="Industry vertical"),
    country: str = Query(..., description="Target country"),
    user: dict = Depends(get_current_user),
):
    industry_data = BUYER_MAP.get(industry)
    if not industry_data:
        available = INDUSTRIES
        raise Exception(f"Industry '{industry}' not found. Available: {available}")

    buyer_data = industry_data.get(country, DEFAULT_BUYER.copy())

    return {
        "success": True,
        "industry": industry,
        "country": country,
        "buyer": buyer_data,
        "found": country in industry_data,
    }


@buyer_map_router.get("/industries")
async def list_industries(user: dict = Depends(get_current_user)):
    return {"success": True, "industries": INDUSTRIES, "total": len(INDUSTRIES)}


@buyer_map_router.get("/countries")
async def list_countries(user: dict = Depends(get_current_user)):
    country_difficulty = {}
    for ind_data in BUYER_MAP.values():
        for country, data in ind_data.items():
            if country not in country_difficulty:
                country_difficulty[country] = []
            country_difficulty[country].append(data.get("entry_difficulty", "medium"))

    result = []
    for country in ALL_COUNTRIES:
        difficulties = country_difficulty.get(country, ["medium"])
        score_map = {"easy": 1, "medium": 2, "hard": 3}
        avg_score = sum(score_map.get(d, 2) for d in difficulties) / len(difficulties)
        if avg_score < 1.5:
            overall = "easy"
        elif avg_score < 2.5:
            overall = "medium"
        else:
            overall = "hard"
        result.append({"country": country, "entry_difficulty": overall, "data_points": len(difficulties)})

    result.sort(key=lambda x: ({"easy": 0, "medium": 1, "hard": 2}[x["entry_difficulty"]], x["country"]))
    return {"success": True, "countries": result, "total": len(result)}


@buyer_map_router.get("/quick-insights")
async def quick_insights(user: dict = Depends(get_current_user)):
    """Top 6 easiest industry+country combos for entry"""
    easy_combos = []
    for industry, countries in BUYER_MAP.items():
        for country, data in countries.items():
            if data.get("entry_difficulty") == "easy":
                easy_combos.append({
                    "industry": industry,
                    "country": country,
                    "primary_buyer": data["primary_buyer"],
                    "deal_cycle": data["typical_deal_cycle"],
                    "entry_difficulty": "easy",
                    "note": data["notes"][:100] + "..." if len(data["notes"]) > 100 else data["notes"],
                })

    return {"success": True, "insights": easy_combos[:12], "total": len(easy_combos)}
