"""Signal CRM — Compliance Layer (Supabase)"""
from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel
from app.auth import get_current_user
from app.database import get_db
from app.models import User, ComplianceSave
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from fastapi import Depends


compliance_router = APIRouter(prefix="/compliance", tags=["Compliance"])

COMPLIANCE_DATA = {
    "Germany": {"framework": "GDPR", "law": "BDSG + EU GDPR", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Explicit consent required for cold email", "Data subject rights: access, deletion, portability", "DPA registration if processing EU resident data", "Data residency: EU storage preferred"], "regulator": "BfDI (Federal Commissioner for Data Protection)", "risk_level": "high", "notes": "Germany enforces GDPR strictly. Cold outreach requires legitimate interest basis + easy opt-out. B2B slightly more lenient than B2C."},
    "France": {"framework": "GDPR + CNIL", "law": "EU GDPR + French Data Protection Act", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Prior consent for B2C cold email", "Legitimate interest possible for B2B", "CNIL registration for certain processing", "French language required for privacy notices"], "regulator": "CNIL", "risk_level": "high", "notes": "CNIL is one of Europe's most active data protection authorities. Document all legitimate interest assessments."},
    "UK": {"framework": "UK GDPR + PECR", "law": "UK GDPR, Data Protection Act 2018, PECR", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to £17.5M or 4% global turnover", "key_rules": ["Legitimate interest basis for B2B cold email", "Must include unsubscribe in every email", "ICO registration required if processing personal data", "PECR applies to electronic marketing"], "regulator": "ICO (Information Commissioner's Office)", "risk_level": "medium", "notes": "UK diverged from EU GDPR post-Brexit. B2B cold email allowed under legitimate interest if relevant and with opt-out."},
    "USA": {"framework": "CAN-SPAM + CCPA", "law": "CAN-SPAM Act, CCPA (California), state laws", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to $51,744 per violation (CAN-SPAM)", "key_rules": ["No deceptive subject lines", "Physical mailing address required", "Clear unsubscribe mechanism", "CCPA: right to opt-out of data sale (California)"], "regulator": "FTC + State AGs", "risk_level": "low", "notes": "US federal law (CAN-SPAM) is permissive. California CCPA applies if you have CA customers. B2B cold email widely practiced."},
    "Canada": {"framework": "CASL", "law": "Canada's Anti-Spam Legislation (CASL)", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to CAD $10M per violation", "key_rules": ["Express or implied consent required", "Identify sender clearly", "Include unsubscribe mechanism", "Implied consent: existing business relationship within 2 years"], "regulator": "CRTC, CRTC Competition Bureau", "risk_level": "high", "notes": "CASL is one of the strictest anti-spam laws. Implied consent exists if prior business relationship. Express consent best practice."},
    "India": {"framework": "DPDP Act 2023", "law": "Digital Personal Data Protection Act 2023", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to ₹250 crore per violation", "key_rules": ["Consent required for processing personal data", "Data Principal rights: access, correction, erasure", "Cross-border transfer restrictions apply", "B2B cold email generally permitted"], "regulator": "Data Protection Board of India", "risk_level": "medium", "notes": "DPDP Act 2023 is India's first comprehensive data protection law. B2B outreach generally fine but consumer data needs consent."},
    "Australia": {"framework": "Spam Act + Privacy Act", "law": "Spam Act 2003, Privacy Act 1988", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to AUD $2.2M per day for serious breaches", "key_rules": ["Inferred consent for B2B", "Unsubscribe must work within 5 business days", "No misleading subject lines", "Privacy Act: data breach notification required"], "regulator": "ACMA, OAIC", "risk_level": "low", "notes": "Australia's Spam Act allows B2B email with inferred consent (visible email address). Easy to comply — just include opt-out."},
    "Singapore": {"framework": "PDPA + SPAM Control Act", "law": "Personal Data Protection Act 2012", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to SGD $1M", "key_rules": ["Do Not Call registry must be checked for phone", "Consent or legitimate purpose for email", "Data Protection Trustmark (DPTM) — optional", "Cross-border transfer: recipient country must have adequate protection"], "regulator": "PDPC (Personal Data Protection Commission)", "risk_level": "medium", "notes": "PDPA is relatively business-friendly. B2B email permitted with opt-out. Check DNC registry before phone outreach."},
    "Japan": {"framework": "APPI + Act on Regulation of Transmission", "law": "Act on Protection of Personal Information (APPI)", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to ¥100M for organizations", "key_rules": ["Prior consent required for commercial email", "Opt-out must be honored within 30 days", "Cross-border transfer: third-party consent required", "Japanese language for privacy notices recommended"], "regulator": "PPC (Personal Information Protection Commission)", "risk_level": "high", "notes": "Japan's anti-spam law is strict. Cold email requires prior consent. B2B relationships make implied consent possible but risky."},
    "Brazil": {"framework": "LGPD", "law": "Lei Geral de Proteção de Dados (LGPD)", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to R$50M or 2% of Brazilian revenue", "key_rules": ["Legal basis required for processing (consent, legitimate interest, etc.)", "Data Subject Rights: access, portability, deletion", "DPA officer (Encarregado) required for some companies", "Cross-border transfers restricted"], "regulator": "ANPD (National Data Protection Authority)", "risk_level": "high", "notes": "LGPD closely mirrors GDPR. Legitimate interest may be used for B2B but must be documented. ANPD enforcement increasing."},
    "Netherlands": {"framework": "GDPR + Telecommunicatiewet", "law": "EU GDPR + Dutch Telecommunications Act", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Prior consent for B2C cold email", "Existing customer exception for similar products", "ACM and AP joint enforcement", "Dutch DPA (AP) known for enforcement"], "regulator": "Autoriteit Persoonsgegevens (AP)", "risk_level": "high", "notes": "Netherlands strictly enforces GDPR. Document legitimate interest carefully for B2B. AP has issued large fines."},
    "South Africa": {"framework": "POPIA", "law": "Protection of Personal Information Act 4 of 2013", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to ZAR 10M or 10 years imprisonment", "key_rules": ["Consent required for direct marketing by electronic means", "Must include opt-out in every communication", "Data subject must be able to object to processing", "Cross-border transfer: adequate protection required"], "regulator": "Information Regulator (POPIA)", "risk_level": "high", "notes": "POPIA fully enforced since July 2021. B2B cold email needs consent or existing relationship. CIPC registration for data processors."},
    "UAE": {"framework": "PDPL (Abu Dhabi) + DIFC + ADGM", "law": "UAE Personal Data Protection Law 2023", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to AED 20M", "key_rules": ["Consent for processing sensitive data", "Data subject rights: access, correction", "Cross-border transfer: adequate protection required", "DIFC/ADGM have their own stricter frameworks"], "regulator": "UAE Data Office", "risk_level": "medium", "notes": "UAE federal PDPL 2023 enacted. B2B email generally permitted. DIFC companies follow stricter rules. Dubai International zones may differ."},
    "Saudi Arabia": {"framework": "PDPL", "law": "Personal Data Protection Law (PDPL)", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to SAR 5M", "key_rules": ["Explicit consent required for marketing communication", "Data residency in Saudi Arabia for sensitive data", "Cross-border transfer restrictions", "Data Steward registration required"], "regulator": "SDAIA / NDMO", "risk_level": "high", "notes": "Saudi PDPL effective September 2023. Strict consent requirements. Data residency rules for certain sectors. Government procurement requires local data."},
    "Malaysia": {"framework": "PDPA", "law": "Personal Data Protection Act 2010", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to MYR 500,000 / 3 years imprisonment", "key_rules": ["Must give opt-out for direct marketing", "Can only process data with consent or legal basis", "Data user registration required for certain categories", "Cross-border transfer: adequate protection required"], "regulator": "PDPD (Personal Data Protection Department)", "risk_level": "medium", "notes": "Malaysia PDPA is relatively permissive. B2B cold email permitted with opt-out. Registration required for data processors in certain sectors."},
    "Indonesia": {"framework": "PDP Law 2022", "law": "Personal Data Protection Law No. 27 of 2022", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to IDR 50B / 5 years imprisonment", "key_rules": ["Explicit consent required for processing", "Right to erasure and correction", "Cross-border transfer: MOU with recipient country", "Data Protection Officer (DPO) required for large processors"], "regulator": "Ministry of Communications and Information Technology", "risk_level": "high", "notes": "Indonesia's PDP Law fully effective 2024. Strict consent requirements. B2B cold email needs explicit consent or legitimate interest documentation."},
    "Sweden": {"framework": "GDPR + DMAL", "law": "EU GDPR + Swedish Direct Marketing Act", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Prior consent for commercial email", "SPAR registry must be consulted", "IMY (Swedish Privacy Authority) actively enforces", "Legitimate interest requires LIA documentation"], "regulator": "IMY (Integritetsskyddsmyndigheten)", "risk_level": "high", "notes": "Sweden is strict on GDPR. IMY has issued significant fines. Document legitimate interest assessments carefully."},
    "Spain": {"framework": "GDPR + LSSICE", "law": "EU GDPR + Spanish Information Society Services Law", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover + LSSICE fines", "key_rules": ["Prior consent for electronic direct marketing", "AEPD known for enforcement actions", "Right to erasure ('right to be forgotten')", "Spanish language for notices required"], "regulator": "AEPD (Spanish Data Protection Agency)", "risk_level": "high", "notes": "AEPD is one of Europe's most active regulators. Cold email requires prior opt-in. B2B legitimate interest possible but risky."},
    "Italy": {"framework": "GDPR + Italian Privacy Code", "law": "EU GDPR + Legislative Decree 196/2003", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Explicit consent for email marketing", "Garante (Italian DPA) very active", "Soft opt-in for existing customers", "Cookie consent must be explicit"], "regulator": "Garante per la protezione dei dati personali", "risk_level": "high", "notes": "Garante is proactive and issues large fines. Cold email strictly requires consent. Existing customer relationship enables limited email."},
    "Mexico": {"framework": "LFPDPPP", "law": "Ley Federal de Protección de Datos Personales en Posesión de los Particulares", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to MXN 320M", "key_rules": ["Privacy notice required (Aviso de Privacidad)", "Right to revoke consent", "B2B email with opt-out generally permitted", "INAI oversees compliance"], "regulator": "INAI", "risk_level": "medium", "notes": "Mexico's law is less strict than GDPR. B2B cold email permitted with proper privacy notice and opt-out. INAI enforcement is increasing."},
    "Argentina": {"framework": "PDPL 25.326", "law": "Personal Data Protection Law 25.326", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to ARS 3M", "key_rules": ["Registration with AAIP required for data processing", "Opt-out for direct marketing", "Sensitive data requires explicit consent", "Cross-border transfer requires adequate protection"], "regulator": "AAIP (Agencia de Acceso a la Información Pública)", "risk_level": "medium", "notes": "Argentina has GDPR adequacy status. B2B cold email permitted with opt-out. Register data processing activities with AAIP."},
    "Nigeria": {"framework": "NDPR + NITDA", "law": "Nigeria Data Protection Regulation 2019", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to NGN 10M or 2% of annual gross revenue", "key_rules": ["Data Audit required annually", "Consent or legitimate interest for processing", "DPIA required for large-scale processing", "NDPC (Nigeria Data Protection Commission) oversees"], "regulator": "NDPC", "risk_level": "medium", "notes": "Nigeria NDPR 2019 + NDPA 2023. B2B email generally permitted. Annual data audit required. Fintech sector faces stricter CBN requirements."},
    "Kenya": {"framework": "DPA 2019", "law": "Data Protection Act 2019", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to KES 3M or 1 year imprisonment", "key_rules": ["Consent or legitimate interest for processing", "Data protection registration required", "Data subject rights: access, correction", "Office of the Data Protection Commissioner (ODPC) enforces"], "regulator": "ODPC", "risk_level": "medium", "notes": "Kenya DPA 2019 is actively enforced. B2B email with legitimate interest permitted. Registration with ODPC required for data processors."},
    "Poland": {"framework": "GDPR + UODO", "law": "EU GDPR + Polish Personal Data Protection Office Act", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Consent for electronic marketing", "UODO (Polish DPA) enforcement active", "Data breach notification: 72 hours", "Legitimate interest must be documented"], "regulator": "UODO (Urząd Ochrony Danych Osobowych)", "risk_level": "high", "notes": "Poland strictly enforces GDPR. UODO has issued significant fines. B2B cold email needs careful legitimate interest documentation."},
    "Vietnam": {"framework": "Decree 13/2023", "law": "Decree on Personal Data Protection 13/2023", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to VND 100M", "key_rules": ["Consent required for processing personal data", "Data localization: critical data must stay in Vietnam", "Annual data protection impact assessment", "Ministry of Public Security oversight"], "regulator": "Ministry of Public Security (A05)", "risk_level": "high", "notes": "Vietnam Decree 13/2023 fully effective. Strict consent requirements. Data localization for certain categories. Cross-border transfer requires government approval."},
    "Philippines": {"framework": "DPA RA 10173", "law": "Data Privacy Act of 2012 (Republic Act 10173)", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to PHP 5M / 6 years imprisonment", "key_rules": ["Consent required for direct marketing", "NPC registration for personal information controllers", "Data breach notification within 72 hours", "Data Subject Rights: access, rectification, erasure"], "regulator": "NPC (National Privacy Commission)", "risk_level": "high", "notes": "Philippines DPA is strictly enforced by NPC. NPC registration required. Cold email needs consent. Existing customer soft opt-in permitted."},
    "Thailand": {"framework": "PDPA", "law": "Personal Data Protection Act B.E. 2562 (2019)", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to THB 5M / 1 year imprisonment", "key_rules": ["Explicit consent for direct marketing", "Right to withdraw consent", "DPO required for large-scale processing", "Cross-border transfer: adequate protection required"], "regulator": "PDPC (Personal Data Protection Committee)", "risk_level": "high", "notes": "Thailand PDPA fully effective 2022. Strict consent requirements. PDPC enforcement ramping up. B2B with existing relationship may use legitimate interest."},
    "New Zealand": {"framework": "Privacy Act 2020 + Unsolicited Electronic Messages Act", "law": "Privacy Act 2020, UEMA 2007", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to NZD 10,000 per violation", "key_rules": ["Unsubscribe must work within 5 days", "Inferred consent for B2B email", "Mandatory breach notification under Privacy Act 2020", "Accurate sender identification required"], "regulator": "Office of the Privacy Commissioner (OPC)", "risk_level": "low", "notes": "Very similar to Australia. B2B cold email permitted with inferred consent and opt-out. Low enforcement risk. Auckland and Wellington are primary markets."},
    "Switzerland": {"framework": "nDSG 2023 (Revised Federal Act on Data Protection)", "law": "Bundesgesetz über den Datenschutz (nDSG) 2023", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to CHF 250,000 (criminal sanctions on individuals)", "key_rules": ["Legitimate interest basis for B2B cold email", "Privacy notice required (German/French/Italian by region)", "DPO required for large-scale systematic processing", "Cross-border transfers: adequacy or standard contractual clauses"], "regulator": "FDPIC (Federal Data Protection and Information Commissioner)", "risk_level": "medium", "notes": "Swiss nDSG closely mirrors GDPR but has some stricter provisions. B2B cold email permitted under legitimate interest. Zurich (finance, tech), Geneva (international orgs), Basel (pharma) are key markets."},
    "Belgium": {"framework": "GDPR + Belgian Data Protection Act", "law": "EU GDPR + Belgian Act of 30 July 2018", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Prior consent required for direct electronic marketing", "APD/GBA actively enforces GDPR", "Legitimate interest requires documented LIA for B2B", "Dutch language in Flanders, French in Wallonia for notices"], "regulator": "APD / GBA (Gegevensbeschermingsautoriteit)", "risk_level": "high", "notes": "Belgium strictly enforces GDPR — Brussels is EU capital with high privacy awareness. Document all legitimate interest assessments. Ghent and Antwerp are tech/manufacturing hubs."},
    "Denmark": {"framework": "GDPR + Databeskyttelsesloven", "law": "EU GDPR + Danish Data Protection Act 2018", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Opt-in consent for all electronic marketing", "Datatilsynet enforcement active", "Soft opt-in permitted for existing customers on similar products", "DPO required for systematic large-scale processing"], "regulator": "Datatilsynet (Danish Data Protection Agency)", "risk_level": "high", "notes": "Denmark has high GDPR compliance culture. Datatilsynet issues significant fines. Copenhagen is Scandinavian tech hub (MedTech, CleanTech, FinTech). Strong sustainability credentials valued by buyers."},
    "Norway": {"framework": "GDPR (EEA) + Personopplysningsloven + Markedsføringsloven", "law": "Norwegian Personal Data Act 2018 + Marketing Control Act", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to NOK 100M or 4% global turnover", "key_rules": ["Prior consent required for commercial electronic messages", "Marketing Control Act is stricter than GDPR on direct marketing", "Datatilsynet actively enforces", "Norwegian language preferred for mid-market"], "regulator": "Datatilsynet", "risk_level": "high", "notes": "Norway implements GDPR via EEA agreement. Marketing Control Act adds strict additional layer. High-trust culture — referrals work far better than cold outreach. Oslo is FinTech, shipping, and energy hub."},
    "Finland": {"framework": "GDPR + Tietosuojalaki", "law": "EU GDPR + Finnish Data Protection Act 2018", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Explicit consent required for email marketing", "Tietosuojavaltuutettu enforcement increasing", "Finnish language notices expected for consumer-facing", "DPO required for systematic large-scale processing"], "regulator": "Tietosuojavaltuutettu (Office of the Data Protection Ombudsman)", "risk_level": "high", "notes": "Finland strictly follows GDPR. Very direct communication culture. Helsinki tech hub (Nokia, Rovio, Supercell ecosystem). Gaming, cleantech, and health tech are hot sectors."},
    "Israel": {"framework": "Protection of Privacy Law (PPIL) 1981 + Regulations 2017", "law": "PPIL 1981, Privacy Protection Regulations 2017", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to ILS 3.22M + criminal sanctions", "key_rules": ["Opt-out mechanism required in all marketing emails", "Database registration with PPA for certain data types", "New Privacy Protection Law in draft — closer to GDPR", "PPA actively updating enforcement approach"], "regulator": "PPA (Privacy Protection Authority)", "risk_level": "low", "notes": "Israel has EU GDPR adequacy status. B2B cold email widely practiced in Israeli tech culture. Very fast decision-making (Sun–Thu work week). English native in tech. Tel Aviv is a world top-10 startup hub."},
    "South Korea": {"framework": "PIPA (Personal Information Protection Act)", "law": "PIPA 2011, revised 2023", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to KRW 3B or 3% of revenue + criminal sanctions", "key_rules": ["Explicit prior consent required for collection and marketing", "Mandatory disclosure when sharing data with 3rd parties", "Data residency: certain categories must stay in Korea", "Korean language privacy notices mandatory"], "regulator": "PIPC (Personal Information Protection Commission)", "risk_level": "high", "notes": "South Korea has one of Asia's strictest privacy regimes. B2B cold email is legally risky — use referral, inbound, or local partner strategy. Local entity or reseller strongly recommended. Seoul is major tech/semiconductor hub."},
    "Taiwan": {"framework": "Personal Data Protection Act (PDPA Taiwan)", "law": "PDPA 2010, amended 2015", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to TWD 50M + criminal sanctions", "key_rules": ["Purpose limitation — use data only for stated purpose", "Data subject rights: access, correction, deletion, stop processing", "Sensitive data requires explicit consent", "Government authority filing for sensitive data categories"], "regulator": "National Development Council (NDC)", "risk_level": "medium", "notes": "Taiwan PDPA is moderate. B2B cold email with opt-out generally permitted. Key sectors: semiconductor (TSMC), electronics, ICT. Mandarin materials for mid-market; English fine for enterprise tech."},
    "Hong Kong": {"framework": "Personal Data (Privacy) Ordinance (PDPO)", "law": "PDPO Cap. 486 + DPSA Amendment 2021", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to HKD 1M + imprisonment", "key_rules": ["Opt-out for direct marketing mandatory in every email", "DPSA 2021: enhanced enforcement and criminal penalties", "Data access and correction rights within 40 days", "Cross-border transfer: recipient country must have adequate protection"], "regulator": "PCPD (Privacy Commissioner for Personal Data)", "risk_level": "medium", "notes": "Hong Kong PDPO is relatively business-friendly. B2B cold email with opt-out permitted. Financial services very regulated (SFC/HKMA). Asia Pacific HQ hub for many MNCs. Cantonese and English market."},
    "Chile": {"framework": "Law 19.628 + Draft Bill 11144 (pending)", "law": "Ley de Protección de Datos Personales No. 19.628", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to CLP 50M under current law", "key_rules": ["Right to access, correct, and delete personal data", "Opt-out for direct marketing must be honoured", "Comprehensive new law (Bill 11144) pending — GDPR-like", "Spanish language required for all privacy notices"], "regulator": "Consejo para la Transparencia", "risk_level": "low", "notes": "Chile has EU GDPR adequacy status. New comprehensive law pending — prepare now. Santiago is most advanced B2B tech market in South America. Mining, fintech, and agritech are primary sectors."},
    "Colombia": {"framework": "Ley 1581/2012 + Decree 1377/2013", "law": "Ley Estatutaria 1581 de Protección de Datos Personales", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to COP 2,000M per violation", "key_rules": ["Registration with National Database Registry (RNBD)", "Habeas data rights: access, correction, deletion, right to oppose", "Privacy notice (Aviso de Privacidad) required", "Spanish language mandatory"], "regulator": "SIC (Superintendencia de Industria y Comercio)", "risk_level": "medium", "notes": "Colombia has active data protection framework. B2B cold email with privacy notice and opt-out. Bogotá and Medellín (Silicon Andino) are tech hubs. SIC enforcement increasing."},
    "Portugal": {"framework": "GDPR + Lei 58/2019", "law": "EU GDPR + Portuguese Data Protection Law 58/2019", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Prior consent required for electronic direct marketing", "CNPD actively enforces GDPR", "Portuguese language required for privacy notices", "Same GDPR rules — CNPD calls it RGPD locally"], "regulator": "CNPD (Comissão Nacional de Proteção de Dados)", "risk_level": "high", "notes": "Portugal strictly enforces GDPR. Lisbon is Europe's fastest-growing tech hub (Web Summit city). Portuguese-language materials required. Note: Brazilian Portuguese differs — create separate materials per market."},
    "Czech Republic": {"framework": "GDPR + Czech Act No. 110/2019", "law": "EU GDPR + Czech Personal Data Processing Act 2019", "cold_email_allowed": False, "opt_in_required": True, "penalty": "Up to €20M or 4% global turnover", "key_rules": ["Consent required for electronic marketing", "UOOU enforcement active but moderate", "Czech language notices expected for local market", "Records of processing activities required"], "regulator": "UOOU (Office for Personal Data Protection)", "risk_level": "medium", "notes": "Czech Republic has large IT outsourcing market (Prague, Brno). GDPR enforcement moderate. B2B with legitimate interest documentation possible. Strong automotive and manufacturing supply chain."},
    "Qatar": {"framework": "PDPPL (Personal Data Privacy Protection Law No. 13/2016)", "law": "Law No. 13 of 2016 on Personal Data Privacy Protection", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to QAR 5M", "key_rules": ["Consent or legitimate interest basis for processing", "Data residency requirements for Qatar resident data", "Cross-border transfer requires regulator approval", "Arabic language notices required for consumer communications"], "regulator": "NCSA (National Cyber Security Agency)", "risk_level": "medium", "notes": "Qatar's PDPPL is moderate. B2B cold email with opt-out permitted. Post-FIFA World Cup infrastructure. Finance, construction, and LNG sectors dominate. Doha growing as MENA hub."},
    "Kuwait": {"framework": "Electronic Communications Law + Draft Data Protection", "law": "Law No. 20 of 2014 on Electronic Communications", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Variable under communications law", "key_rules": ["No comprehensive data protection law yet", "Electronic communications law applies to spam", "Government and banking sector very restrictive", "Arabic preferred for all business communication"], "regulator": "CITRA (Communications and IT Regulatory Authority)", "risk_level": "low", "notes": "Kuwait lacks comprehensive data protection law. B2B cold email generally practiced. Private sector faster than government. Oil, finance, and retail sectors dominant. Kuwait City is primary hub."},
    "Bahrain": {"framework": "PDPL 2018 (Decree-Law No. 30)", "law": "Bahrain Personal Data Protection Law 2018", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to BHD 20,000 + criminal sanctions", "key_rules": ["Legitimate interest or consent for data processing", "PDPA registration required for data controllers", "Cross-border transfer: adequate protection required", "Data subject rights: access, correction, erasure"], "regulator": "PDPA (Personal Data Protection Authority Bahrain)", "risk_level": "medium", "notes": "Bahrain was first GCC country with comprehensive data protection law. Business-friendly environment. FinTech, Islamic finance, and logistics hub. Bahrain Financial Harbour. Fastest deal cycle in Gulf."},
    "Morocco": {"framework": "Law 09-08 + CNDP oversight", "law": "Loi 09-08 relative à la protection des personnes physiques à l'égard du traitement des données à caractère personnel", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to MAD 300,000", "key_rules": ["CNDP authorization for certain data processing categories", "Cross-border transfer requires CNDP authorization", "French and Arabic language notices required", "Right to access and oppose data processing"], "regulator": "CNDP (Commission Nationale de contrôle de la protection des Données)", "risk_level": "medium", "notes": "French-influenced privacy law. B2B cold email permitted with opt-out. Casablanca is primary business hub — Africa's gateway for European expansion. French materials strongly preferred."},
    "Pakistan": {"framework": "PECA 2016 + Draft Personal Data Protection Bill", "law": "Prevention of Electronic Crimes Act (PECA) 2016", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to PKR 5M under PECA", "key_rules": ["PECA applies to unauthorized data access and spam", "Draft PDPB pending — GDPR-like when enacted", "FIA oversees cybercrime enforcement", "Limited enforcement for B2B commercial email currently"], "regulator": "FIA + NTISB", "risk_level": "low", "notes": "Pakistan's comprehensive data protection law still in draft. B2B enforcement very limited currently. Large IT outsourcing market. Karachi, Lahore, Islamabad are main tech hubs. Growing export of tech talent."},
    "Ghana": {"framework": "Data Protection Act 2012 (Act 843)", "law": "Data Protection Act 843 of 2012", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to GHS 5,000 per violation / GHS 2.5M for companies", "key_rules": ["Registration with Data Protection Commission required", "Consent or legitimate interest for processing", "Right to access and correct personal data", "Data breach reporting required to DPC"], "regulator": "DPC (Data Protection Commission Ghana)", "risk_level": "low", "notes": "Ghana has established data protection law but limited enforcement. Accra is West Africa's growing tech hub. FinTech, agritech, and oil sectors active. English-native market. Strong startup scene."},
    "Uganda": {"framework": "Data Protection and Privacy Act 2019", "law": "DPPA 2019", "cold_email_allowed": True, "opt_in_required": False, "penalty": "Up to UGX 250M or 10% of annual turnover", "key_rules": ["Consent or legitimate interest for processing", "Data collector registration with PDPC", "Data subject rights: access, correction, erasure", "Cross-border transfers: adequate protection required"], "regulator": "PDPC (Personal Data Protection Office Uganda)", "risk_level": "low", "notes": "Uganda enacted DPPA in 2019. Growing tech hub (Kampala — 'Silicon Savannah' node). Mobile money and agritech are key sectors. English-native market."},
}


class SaveComplianceReq(BaseModel):
    country: str
    notes: str = ""


@compliance_router.get("/countries")
def get_countries():
    return {
        "success": True,
        "countries": [
            {"country": k, "framework": v["framework"], "risk_level": v["risk_level"],
             "cold_email_allowed": v["cold_email_allowed"]}
            for k, v in COMPLIANCE_DATA.items()
        ],
        "total": len(COMPLIANCE_DATA),
    }


@compliance_router.get("/check")
def check_compliance(country: str = Query(...)):
    data = COMPLIANCE_DATA.get(country)
    if not data:
        available = sorted(COMPLIANCE_DATA.keys())
        return {"success": False, "message": f"No data for '{country}'.", "available_countries": available}
    return {"success": True, "country": country, **data}


@compliance_router.post("/save")
async def save_compliance(req: SaveComplianceReq, user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):
    data = COMPLIANCE_DATA.get(req.country, {})
    save = ComplianceSave(user_id=user.id, country=req.country, framework=data.get("framework", ""), notes=req.notes)
    db.add(save)
    await db.commit()
    await db.refresh(save)
    return {"success": True, "saved": {"id": save.id, "country": save.country}, "message": f"Saved compliance note for {req.country}."}


@compliance_router.get("/saved")
async def get_saved(user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):
    r = await db.execute(select(ComplianceSave).where(ComplianceSave.user_id == user.id).order_by(ComplianceSave.created_at.desc()))
    items = r.scalars().all()
    return {"success": True, "saved": [{"id": s.id, "country": s.country, "framework": s.framework, "notes": s.notes} for s in items]}
